### ISSUE TITLE
Quay Build Notifications

### ISSUE THREAD

**Issue by ortwinschneider** [sa-mw-dach/manuela-gitops#3]

**Comment by ortwinschneider** [comment]
The cat went here and there
And the moon spun round like a top,
And the nearest kin of the moon,
The creeping cat, looked up.
Black Minnaloushe stared at the moon,
For, wander and wail as he would,
The pure cold light in the sky
Troubled his animal blood.

**Comment by ortwinschneider** [comment]
new version of quay.io iot-consumer image available in Quay.

**Comment by ortwinschneider** [comment]
new version of quay.io iot-consumer image available in Quay.

**Comment by ortwinschneider** [comment]
Tekton sensor-pipeline: New version of quay.io/manuela/iot-software-sensor available.

**Comment by ortwinschneider** [comment]
Tekton iot-dashboard-pipeline: New version of quay.io/manuela/iot-frontend and quay.io/manuela/iot-consumer available.

**Comment by ortwinschneider** [comment]
Tekton iot-dashboard-pipeline: New version of quay.io/manuela/iot-frontend and quay.io/manuela/iot-consumer available.

**Comment by ortwinschneider** [comment]
Tekton sensor-pipeline: New version of quay.io/manuela/iot-software-sensor available.

**Comment by ortwinschneider** [comment]
Tekton sensor-pipeline: New version of quay.io/manuela/iot-software-sensor available.

**Comment by ortwinschneider** [comment]
New version available

**Comment by ortwinschneider** [comment]
New version available

**Comment by ortwinschneider** [comment]
Tekton iot-consumer-pipeline; There is a new version of quay.io/manuela/iot-consumer available.

**Comment by ortwinschneider** [comment]
Tekton iot-consumer-pipeline; There is a new version of quay.io/manuela/iot-consumer available.

**Comment by ortwinschneider** [comment]
Tekton iot-consumer-pipeline; There is a new version of quay.io/manuela/iot-consumer available.

**Comment by ortwinschneider** [comment]
Tekton iot-consumer-pipeline; There is a new version of quay.io/manuela/iot-consumer available.

**Comment by ortwinschneider** [comment]
Tekton iot-consumer-pipeline; There is a new version of quay.io/manuela/iot-consumer available.

**Comment by ortwinschneider** [comment]
Tekton iot-consumer-pipeline; There is a new version of quay.io/manuela/iot-consumer available.

**Comment by ortwinschneider** [comment]
Tekton iot-consumer-pipeline; There is a new version of quay.io/manuela/iot-consumer available.

**Comment by ortwinschneider** [comment]
Tekton iot-consumer-pipeline; There is a new version of quay.io/manuela/iot-consumer available.

**Comment by ortwinschneider** [comment]
Tekton iot-consumer-pipeline; There is a new version of quay.io/manuela/iot-consumer available.

**Comment by ortwinschneider** [comment]
Tekton iot-consumer-pipeline; There is a new version of quay.io/manuela/iot-consumer available.

**Comment by ortwinschneider** [comment]
Tekton iot-consumer-pipeline; There is a new version of quay.io/manuela/iot-consumer available.

**Comment by DanielFroehlich** [comment]
Tekton iot-consumer-pipeline; There is a new version of quay.io/manuela/iot-consumer available.

**Comment by DanielFroehlich** [comment]
Tekton iot-consumer-pipeline; There is a new version of quay.io/manuela/iot-consumer available.

**Comment by wrichter** [comment]
Tekton iot-consumer-pipeline; There is a new version of quay.io/manuela/iot-consumer available.

**Comment by wrichter** [comment]
Tekton iot-consumer-pipeline; There is a new version of quay.io/manuela/iot-consumer available.
